
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-3
  region: us-east-1

nodeGroups:
  - name: ng1-public
    instanceType: t2.micro
    instanceName: custom-node-name
    desiredCapacity: 2
  - name: ng2-private
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
