name: Github Actions Example

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./dir1
     

    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::321089933200:role/testrone
        aws-region: us-east-1

    - name: Copy files to the test website with AWS  CLI
      run: |
        aws s3 ls
  
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (needs.test.result == 'success')
    steps:
      - name: Needs context
        run: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp;sudo mv /tmp/eksctl /usr/local/bin;eksctl version
      - name: Run Eks
        run: |
            pwd
